package br.com.tokiomarine.seguradora.vistoriaprevia.servico.configs.auth;

public enum RecoverSessionType {

	COOKIE_NAME("PORTAL_COOKIE"),

	// DADOS NO HEADER **
	ID_KEY("ID"),
	IDUSUARIOPORTAL_KEY("IDUSUARIOPORTAL"),
	LOGIN_KEY("LOGIN"),
	NOME_KEY("NOME"),
	CPF_KEY("CPF"),

	// DADOS NO COOKIE **
	// O valor do codigo interno eh utilizado apenas para corretor,
	// preenchido com o codigo TMS do corretor selecionado na combobox.
	CODIGOINTERNO_KEY("COD_INTERNO"),
	SITEORIGEM_KEY("SITEORIGEM"),

	IDPARCEIRONEGOCIOPRIMARIO_KEY("ID_PARCEIRO_NEGOCIO_PRIMARIO"),
	CODIGOPARCEIRONEGOCIOPRIMARIO_KEY("CODIGO_PARCEIRO_NEGOCIO_PRIMARIO"),
	NOMEPARCEIRONEGOCIOPRIMARIO_KEY("NOME_PARCEIRO_NEGOCIO_PRIMARIO"),
	TIPOPARCEIRONEGOCIOPRIMARIO_KEY("TIPO_PARCEIRO_NEGOCIO_PRIMARIO"),
	PREPOSTO_PARCEIRONEGOCIOPRIMARIO_KEY("PREPOSTO_NEGOCIO_PRIMARIO"),
	INDICADORVENDA_PARCEIRONEGOCIOPRIMARIO_KEY("INDICADORVENDA_PARCEIRO_NEGOCIO_PRIMARIO"),
	CONTACORRENTE_PARCEIRONEGOCIOPRIMARIO_KEY("CONTACORRENTE_PARCEIRO_NEGOCIO_SPRIMARIO"),

	IDPARCEIRONEGOCIOSECUNDARIO_KEY("ID_PARCEIRO_NEGOCIO_SECUNDARIO"),
	CODIGOPARCEIRONEGOCIOSECUNDARIO_KEY("CODIGO_PARCEIRO_NEGOCIO_SECUNDARIO"),
	NOMEPARCEIRONEGOCIOSECUNDARIO_KEY("NOME_PARCEIRO_NEGOCIO_SECUNDARIO"),
	TIPOPARCEIRONEGOCIOSECUNDARIO_KEY("TIPO_PARCEIRO_NEGOCIO_SECUNDARIO"),
	PREPOSTO_PARCEIRONEGOCIOSECUNDARIO_KEY("PREPOSTO_NEGOCIO_SECUNDARIO"),
	INDICADORVENDA_PARCEIRONEGOCIOSECUNDARIO_KEY("INDICADORVENDA_PARCEIRO_NEGOCIO_SECUNDARIO"),
	CONTACORRENTE_PARCEIRONEGOCIOSECUNDARIO_KEY("CONTACORRENTE_PARCEIRO_NEGOCIO_SECUNDARIO"),
	TIPOSITE("TIPOSITE"),

	TOTAL_CONCESSIONARIAS_RELACIONADAS("TOTAL_CONCESSIONARIAS_RELACIONADAS"),

	//Usuario do portal corretor	 
	CODIGO_USUARIO_PORTAL("CODIGO_USUARIO_PORTAL"),
	LOGIN_USUARIO_PORTAL("LOGIN_USUARIO_PORTAL"),
	TIPO_USUARIO_PORTAL("TIPO_USUARIO_PORTAL"),
	CODIGO_ASSESSORIA_PORTAL("CODIGO_ASSESSORIA_PORTAL"),
	IS_WEB("isWEB"),
	CODIGOINTERNO("CODIGOINTERNO"),
	USERID("USERID"),
	USERCPF("USERCPF"),
	USERPREPOSTO("USERPREPOSTO"),

	//Usuario do SSV	 
	ID_USUARIO_SSV("IDUSUARIO"),
	EMPRESA_USUARIO_SSV("EMPRESAUSUARIO"),
	TIPO_LOCAL_USUARIO_SSV("TIPODELOCALUSUARIO"),
	LOCAL_USUARIO_SSV("LOCALUSUARIO"),
	FUNCAO_USUARIO_SSV("FUNCAOUSUARIO"),

	ORIGEM_CORRETOR("CORRETOR"),
	ORIGEM_CONCESSIONARIA("CONCESSIONARIA"),
	ORIGEM_ASSESSORIA("ASSESSORIA"),
	ID_SISTEMA("ID_SISTEMA");
		
	private final String valor;
    
	RecoverSessionType(String valorOpcao){
        valor = valorOpcao;
    }
    
	public String getValue(){
        return valor;
    }
}
